services:
  news_db:
    image: postgres:15-alpine
    container_name: news-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432

  redis_cache:
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    container_name: redis-cache
    restart: always
    volumes:
      - redis-cache:/data

  news:
    build:
      context: news
      dockerfile: Dockerfile
    container_name: news-service
    depends_on:
      - news_db
      - redis_cache
    ports:
      - 8888:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://news_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_REDIS_HOST=redis_cache
      - SPRING_DATA_REDIS_PORT=6379

volumes:
  redis-cache:
    driver: local