spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clevertec
    username: postgres
    password: postgres
  liquibase:
    contexts: prod
    
server:
  servlet:
    context-path: /api/v1


