spring:
  application:
    name: news-service
  datasource:
    url: jdbc:postgresql://localhost:5432/clevertec
    username: postgres
    password: postgres
  liquibase:
    contexts: prod
  cloud:
    config:
      enabled: false

api:
  path:
    prefix: /api/v1

external:
  service:
    user-data:
      url: 'http://localhost:8081/api/v1/users/'

loggable:
  enabled: true

exception:
  handler:
    enabled: true
