spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clevertec
    username: postgres
    password: postgres

server:
  port: 8081

application:
  security:
    jwt:
      # must be same as in news-service
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      issuer: Clevertec