INSERT INTO news_system.news(title, author, "text", created_at, edited_at)
VALUES ('Breaking News: COVID-19 Vaccine Approved for Emergency Use', 'author',
        'After extensive trials and evaluations, health authorities have granted emergency approval for a new COVID-19 vaccine. The vaccine has shown promising results in preventing the spread of the virus and reducing the severity of symptoms.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Tech Giant Launches Revolutionary Smartphone with AI Assistant', 'author',
        'In a breakthrough move, a leading technology company has unveiled its latest smartphone model featuring an advanced AI assistant. The AI assistant can perform tasks, provide personalized recommendations, and interact with users in a more natural and intuitive manner.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Scientists Discover New Species in Unexplored Rainforest', 'author',
        'During a recent expedition to an unexplored rainforest, scientists stumbled upon a previously unknown species of flora and fauna. This discovery sheds light on the biodiversity of our planet and emphasizes the importance of preserving these untouched ecosystems.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Space Exploration: Astronauts Set New Record for Longest Space Mission', 'author',
        'Astronauts aboard the International Space Station (ISS) have achieved a remarkable milestone by completing the longest continuous space mission in history. This achievement paves the way for future manned missions to explore deep space and beyond.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('New Study Reveals Benefits of Regular Exercise', 'author',
        'A recent study has highlighted the numerous benefits of regular exercise on physical and mental health. The findings suggest that engaging in physical activity can improve cardiovascular fitness, boost mood, and reduce the risk of chronic diseases.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('World Leaders Gather for Global Climate Summit', 'author',
        'Leaders from around the world are convening at the Global Climate Summit to discuss urgent actions to combat climate change. The summit aims to address key environmental issues, promote sustainable practices, and achieve significant reductions in greenhouse gas emissions.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Celebrity Couple Announces Engagement', 'author',
        'In a surprise announcement, a popular celebrity couple has revealed their engagement, sparking excitement among fans and media. The couple, known for their successful careers in the entertainment industry, shared their joy and plans for a future together.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('New Art Exhibition Showcases Local Talent', 'author',
        'A local art gallery is hosting a new exhibition featuring the works of talented artists from the community. The exhibition aims to promote local artistry, creativity, and provide a platform for artists to showcase their unique perspectives through various art forms.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Researchers Make Breakthrough in Cancer Treatment', 'author',
        'Scientists have made a significant breakthrough in cancer research, unveiling a new treatment approach that shows promising results in targeting and combating certain types of cancer cells. This discovery offers new hope for improved cancer therapies and better patient outcomes.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Sports Team Wins Championship in Thrilling Final Match', 'author',
        'In an exhilarating final match, a local sports team emerged victorious and claimed the championship title. The teams exceptional performance, teamwork, and determination were on full display, captivating the audience and leaving a lasting impression on sports enthusiasts.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Tech Startup Raises Millions in Funding Round', 'author',
        'A promising tech startup has successfully secured a substantial amount of funding in its latest funding round. The investment will enable the company to further develop its innovative products, expand its operations, and fuel its growth in the competitive tech industry.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Historic Landmark Reopens After Extensive Restoration', 'author',
        'A historic landmark that holds significant cultural and historical value has reopened its doors to the public following an extensive restoration project. The restoration efforts aimed to preserve the architectural integrity and ensure the continued appreciation of this iconic site.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('New Documentary Sheds Light on Environmental Conservation', 'author',
        'A thought-provoking documentary film has been released, exploring the importance of environmental conservation and raising awareness about pressing ecological issues. The documentary delves into the challenges faced by our planet and emphasizes the need for sustainable practices and collective action.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('World-renowned Chef Opens New Restaurant', 'author',
        'A world-renowned chef known for their culinary expertise and innovative dishes has opened a new restaurant, tantalizing food enthusiasts with a unique dining experience. The restaurant promises to showcase the chef''s culinary mastery, using locally sourced ingredients and delivering a memorable gastronomic journey.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('New Technology Promises Breakthrough in Renewable Energy', 'author',
        'Scientists have developed a groundbreaking technology that has the potential to revolutionize the field of renewable energy. The innovative solution aims to harness and store renewable energy more efficiently, providing a sustainable and cleaner alternative to traditional energy sources.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Local Charity Organization Raises Funds for a Worthy Cause', 'author',
        'A local charity organization has successfully raised a significant amount of funds through community support and donations. The funds will be used to support a worthy cause, making a positive impact on the lives of those in need and contributing to the betterment of the community.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Up-and-Coming Band Releases Highly Anticipated Debut Album', 'author',
        'An up-and-coming musical band has released their highly anticipated debut album, captivating music enthusiasts with their unique sound and creative compositions. The album showcases the band''s talent, passion, and promises to be a remarkable addition to the music industry.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Travel Destination Named Best Tourist Spot of the Year', 'author',
        'A captivating travel destination has been recognized as the best tourist spot of the year, attracting travelers from around the globe with its stunning landscapes, rich culture, and unique experiences. The accolade highlights the destination''s appeal and invites visitors to explore its hidden treasures.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Breakthrough Research Sheds Light on Brain Health', 'author',
        'A breakthrough research study has provided valuable insights into maintaining optimal brain health and preventing cognitive decline. The findings emphasize the importance of lifestyle factors, such as exercise, a balanced diet, and mental stimulation, in promoting brain function and overall well-being.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Artificial Intelligence Technology Transforms Industry', 'author',
        'Artificial intelligence (AI) technology has revolutionized an industry, automating processes, enhancing efficiency, and enabling new possibilities. The integration of AI has streamlined operations, improved decision-making, and paved the way for innovative advancements in the field.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Renowned Author Releases Highly Anticipated Novel', 'author',
        'A renowned author has released their highly anticipated novel, captivating readers with a compelling storyline, vivid characters, and thought-provoking themes. The novel promises to be a literary masterpiece, captivating the imaginations of readers and sparking engaging discussions.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('New Educational Program Aims to Empower Underprivileged Youth', 'author',
        'A new educational program has been launched with the aim of empowering underprivileged youth through quality education and skills development. The program provides access to resources, mentorship, and opportunities, enabling young individuals to overcome barriers and realize their full potential.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Innovative Startup Disrupts Traditional Market', 'author',
        'An innovative startup has disrupted a traditional market by introducing a groundbreaking product or service. The startups disruptive approach challenges the status quo, offering unique solutions, and reshaping the industry landscape.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Local Theater Company Stages Critically Acclaimed Production', 'author',
        'A local theater company has received critical acclaim for its captivating and thought-provoking production. The talented cast and crew have delivered a remarkable theatrical experience, captivating audiences and garnering praise from theater enthusiasts and critics alike.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Breakthrough in Medicine Shows Promise for Rare Disease Treatment', 'author',
        'Medical researchers have achieved a significant breakthrough in the treatment of a rare disease, offering hope to patients and their families. The innovative treatment approach holds promise for improved outcomes and better quality of life for individuals affected by the disease.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('New Study Reveals Benefits of Meditation for Mental Health', 'author',
        'A comprehensive study conducted by researchers has demonstrated the positive impact of meditation on mental health. The findings indicate that regular meditation practice can help reduce stress, anxiety, and improve overall well-being.',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO news_system.comments (news_id, author, "text", created_at, edited_at)
VALUES
-- Comments for news_id = 1
(1, 'author', 'Great article!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'author', 'I completely agree with the points mentioned.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'author', 'Well written and informative.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'author', 'Thanks for sharing this valuable information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'author', 'This article has opened my eyes to a new perspective.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'author', 'I found this article very helpful and insightful.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'author', 'Excellent piece of writing!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'author', 'I would love to read more articles like this.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'author', 'I appreciate the effort put into researching and writing this article.', CURRENT_TIMESTAMP,
 CURRENT_TIMESTAMP),
(1, 'author', 'This article has inspired me to take action.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Comments for news_id = 2
(2, 'author', 'The album is amazing!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'author', 'I can''t stop listening to it.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'author', 'This band has a bright future ahead.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'author', 'The songs are so catchy.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'author', 'I''m impressed by the band''s musical talent.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'author', 'The lyrics are deep and meaningful.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'author', 'I highly recommend giving it a listen.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'author', 'This album exceeded my expectations.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'author', 'I''m already looking forward to their next release.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'author', 'This band deserves all the success.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Comments for news_id = 3
(3, 'author', 'I''ve been to that travel destination and it''s breathtaking.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'author', 'The people there are so friendly and welcoming.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'author', 'I had the best time exploring the local attractions.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'author', 'The food is absolutely delicious!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'author', 'I would love to go back and visit again.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'author', 'The scenery is like something out of a postcard.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'author', 'I highly recommend adding this destination to your travel bucket list.', CURRENT_TIMESTAMP,
 CURRENT_TIMESTAMP),
(3, 'author', 'I''m grateful for the unforgettable memories I made there.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'author', 'It''s a paradise for nature lovers.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'author', 'I can''t wait to share my travel photos with everyone.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Comments for news_id = 4
(4, 'author', 'I learned so much from this article.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'author', 'The author did a great job explaining the concepts.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'author', 'Im glad I stumbled upon this piece of information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'author', 'This article has sparked my interest in the topic.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'author', 'I appreciate the depth of research put into this article.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'author', 'I will be sharing this article with my friends.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'author', 'The insights shared in this article are valuable.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'author', 'Im looking forward to reading more from this author.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'author', 'This article has given me a fresh perspective on the subject.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'author', 'Im inspired to dig deeper into this topic.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Comments for news_id = 5
(5, 'author', 'The plot of the movie kept me on the edge of my seat.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'author', 'The performances by the actors were outstanding.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'author', 'I was emotionally invested in the characters.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'author', 'The cinematography was breathtaking.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'author', 'The movie had a thought-provoking message.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'author', 'Im recommending this movie to all my friends.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'author', 'The soundtrack perfectly complemented the scenes.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'author', 'The movie left a lasting impression on me.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'author', 'I cant wait to watch it again.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'author', 'The director did an amazing job bringing the story to life.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Comments for news_id = 6
(6, 'author', 'Great article!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'author', 'I completely agree with the points mentioned.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'author', 'Well written and informative.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'author', 'Thanks for sharing this valuable information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'author', 'This article has opened my eyes to a new perspective.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'author', 'I found this article very helpful and insightful.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'author', 'Excellent piece of writing!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'author', 'I would love to read more articles like this.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'author', 'I appreciate the effort put into researching and writing this article.', CURRENT_TIMESTAMP,
 CURRENT_TIMESTAMP),
(6, 'author', 'This article has inspired me to take action.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Comments for news_id = 7
(7, 'author', 'The album is amazing!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'author', 'I can''t stop listening to it.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'author', 'This band has a bright future ahead.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'author', 'The songs are so catchy.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'author', 'I''m impressed by the band''s musical talent.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'author', 'The lyrics are deep and meaningful.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'author', 'I highly recommend giving it a listen.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'author', 'This album exceeded my expectations.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'author', 'I''m already looking forward to their next release.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'author', 'This band deserves all the success.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Comments for news_id = 8
(8, 'author', 'I''ve been to that travel destination and it''s breathtaking.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'author', 'The people there are so friendly and welcoming.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'author', 'I had the best time exploring the local attractions.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'author', 'The food is absolutely delicious!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'author', 'I would love to go back and visit again.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'author', 'The scenery is like something out of a postcard.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'author', 'I highly recommend adding this destination to your travel bucket list.', CURRENT_TIMESTAMP,
 CURRENT_TIMESTAMP),
(8, 'author', 'I''m grateful for the unforgettable memories I made there.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'author', 'It''s a paradise for nature lovers.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'author', 'I can''t wait to share my travel photos with everyone.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Comments for news_id = 9
(9, 'author', 'I learned so much from this article.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 'author', 'The author did a great job explaining the concepts.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 'author', 'Im glad I stumbled upon this piece of information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 'author', 'This article has sparked my interest in the topic.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 'author', 'I appreciate the depth of research put into this article.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 'author', 'I will be sharing this article with my friends.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 'author', 'The insights shared in this article are valuable.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 'author', 'Im looking forward to reading more from this author.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 'author', 'This article has given me a fresh perspective on the subject.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 'author', 'Im inspired to dig deeper into this topic.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Comments for news_id = 10
(10, 'author', 'The plot of the movie kept me on the edge of my seat.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'author', 'The performances by the actors were outstanding.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'author', 'I was emotionally invested in the characters.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'author', 'The cinematography was breathtaking.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'author', 'The movie had a thought-provoking message.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'author', 'Im recommending this movie to all my friends.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'author', 'The soundtrack perfectly complemented the scenes.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'author', 'The movie left a lasting impression on me.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'author', 'I cant wait to watch it again.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'author', 'The director did an amazing job bringing the story to life.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);