spring:
  cache:
    type: redis
    redis:
      time-to-live: PT60M # period of time = 60 minutes
  jpa:
    show-sql: true
  data:
    redis:
      port: 6379
      host: localhost
  liquibase:
    contexts: prod
